### ISSUE TITLE
warnings when using adapter

### ISSUE THREAD

**Issue by juranki** [juranki/sveltekit-cdk#10]
Changing adapter to esmodule helped handling issues with fetch shims but now there are warnings and notes when adapter is used. It does seem to work, though.

```

> Using sveltekit-cdk-adapter
 > .svelte-kit/cdk/proxy-v2-handler.js:1:17: warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
     1 │ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
       ╵                  ~~~~
   .svelte-kit/cdk/proxy-v2-handler.js:12:0: note: This file is considered an ECMAScript module because of the "import" keyword here
    12 │ import { log, toRawBody } from './util';
       ╵ ~~~~~~

 > .svelte-kit/cdk/at-edge-handler.js:1:17: warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
     1 │ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
       ╵                  ~~~~
   .svelte-kit/cdk/at-edge-handler.js:12:0: note: This file is considered an ECMAScript module because of the "import" keyword here
    12 │ import { log, toRawBody } from './util';
       ╵ ~~~~~~

  ✔ done
```

**Comment by uNki23** [comment]
Hey! Great repo! I was wondering, did you stop working on it?

**Comment by juranki** [comment]
Hi @uNki23,
Thank you! I'm still working on it, although I can't spend much time on it. I decided that I won't try to follow every turn of sveltekit development until it stabilises and hits 1.0. Currently active development is on #11, where, in addition to the actual issue, the scope of the project is clarified and narrowed to a more opinionated take on how SvelteKit should be deployed on Cloudfront, Lambda@Edge and S3. I should probably merge to make it more visible, even if there are still some lingering problems.

**Comment by juranki** [comment]
@sveltekit-cdk/adapter@0.8.0
