### ISSUE TITLE
Binary request/response body

### ISSUE THREAD

**Issue by juranki** [juranki/sveltekit-cdk#15]
Implement transformations

https://github.com/juranki/sveltekit-cdk/blob/main/packages/adapter/src/files/util.ts#L27-L32
https://github.com/juranki/sveltekit-cdk/blob/main/packages/adapter/src/files/at-edge-handler.ts#L87-L97

**Comment by uNki23** [comment]
What would be a typical scenario for binary request / response bodies? I can imagine file uploads or downloads but would consider S3 for those things?

Thank you! :)

**Comment by juranki** [comment]
Scenarios that require binary are not common, but they do occur. 
- using json alternatives like protobuf, msgpack, etc
- image generation, resizing, cropping, etc. for small images
- pdf generation for small documents

Granted, Lambda@Edge payload size limit can be difficult in many cases with binary content.
But I still feel the adapter is severely incomplete if it only supports text body.
