### ISSUE TITLE
Changes in SvelteKit to align with Vite by remove writeStatic

### ISSUE THREAD

**Issue by HUFGhani** [juranki/sveltekit-cdk#24]
https://github.com/sveltejs/kit/pull/5618 however update to the latest version svelte which is 1.0.0-next.419

**Comment by juranki** [comment]
Thanks!
I'll have a look this weekend.

**Comment by juranki** [comment]
@sveltekit-cdk/adapter@0.8.0 and @sveltekit-cdk/constructsv2@0.3.5 should now work with @sveltejs/kit@1.0.0-next.428

Didn't have time to migrate my test site, so testing has been lighter than usually.
