### ISSUE TITLE
Unable to access site after deployment.

### ISSUE THREAD

**Issue by khuezy** [juranki/sveltekit-cdk#28]
Hi, I have a SST + Sveltkit app and deployed it successfully but I'm getting 503:
`The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions`.

I see in your examples, you have a `cdk.json`, does that provide some global permissions to the CF + Lambda?

**Comment by nbaillie** [comment]
I also see the same error back to the browser from cloudfront, but i can see that the edge function triggers (cloudwatch logs in another region..), is throwing the error bellow:

```
"errorType": "TypeError",
    "errorMessage": "Cannot read properties of null (reading 'handleError')",
    "stack": [
        "TypeError: Cannot read properties of null (reading 'handleError')",
        "    at Object.handle_error (/var/task/handler.js:27249:35)",
        "    at handle_error_and_jsonify (/var/task/handler.js:25098:20)",
        "    at handle_fatal_error (/var/task/handler.js:25081:22)",
        "    at respond (/var/task/handler.js:27104:18)",
        "    at async Runtime.handler (/var/task/handler.js:27448:20)"
    ]
```

**Comment by khuezy** [comment]
Yup, thanks for posting that error - I get the same.

**Comment by nbaillie** [comment]
@khuezy  - after using the adapter with 'yarn build' i edited `[my-cdk-folder]/sveltekit/lambda/at-edge/handler.js`
just above the line 'log("DEBUG", "render input", input);'
I added the 3 lines you can see bellow, works now.. im sure this is not clean.. and is going to disappear next time i build but working for now so i can have a play.

@juranki - I like the idea with this project. :) Nice work.

```ts
const env = {}
log('DEBUG', 'server init with env', env)
await server.init({ env: env })
log("DEBUG", "render input", input);
const rendered = await server.respond(input, {
  getClientAddress() {
    const addrHeader = request.headers["cloudfront-viewer-address"];
    if (addrHeader) {
      return addrHeader[0].value.split(":")[0];
    }
    return "";
  }
});
```

**Comment by juranki** [comment]
@khuezy , @nbaillie  - `@sveltekit-cdk/adapter@0.9.2` and `@sveltekit-cdk/constructsv2@0.4.0` contain the above fix, and other improvements too. The [demo site](https://d18o0et7tfgtse.cloudfront.net) appears to work, but that's the extent of testing at the moment.

Please try these versions and let me know the results.

**Comment by khuezy** [comment]
Thanks @juranki! I'm able to successfully deploy using the latest versions.
Feel free to close this ticket. 

Some questions if I may:
- Since the handlers are using Lambda@Edge, are there any guidelines when writing APIs? From what I understand, there are some limitations.
- Does Lambda@Edge support nodejs 18 yet?
- If using Dynamodb, how do you know the region the Edge function is in to target the closes `region`?

**Comment by juranki** [comment]
@khuezy

- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html lists the restrictions with Lambda@Edge (and CloudFront) functions.
- one of the restrictions is limited set of runtimes; node 18 is not supported yet
- lambda@edge runtime exposes region in environment variable AWS_REGION

Would you file an issue about the build error, please? ConstructsV2 builds both esm and commonjs modules. It might be time to drop commonjs.
