### ISSUE TITLE
Importing @sveltekit-cdk/constructsv2 esm module does not work

### ISSUE THREAD

**Issue by khuezy** [juranki/sveltekit-cdk#30]
When I import via 'import', it somehow targets the `dist/cjs` file. I expect it to reference the `dist/mjs` file.

```
import { SvelteDistribution } from "@sveltekit-cdk/constructsv2";
         ^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'SvelteDistribution' not found. The requested module '@sveltekit-cdk/constructsv2' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@sveltekit-cdk/constructsv2';
const { SvelteDistribution } = pkg;
```

As a workaround, I did this:
```
const pkg = require('@sveltekit-cdk/constructsv2');
const { SvelteDistribution } = pkg;
```

**Comment by juranki** [comment]
I wasn't able to reproduce the error. Tried a build that produced only an esm package, but couldn't get it to work nicely with cdk.

`@sveltekit-cdk/constructsv2@0.5.0` contains only commonjs package, with slightly different build and package config. Could you try that?

**Comment by khuezy** [comment]
Thanks! The new version works great now.
