### ISSUE TITLE
How to handle environmental variables?

### ISSUE THREAD

**Issue by khuezy** [juranki/sveltekit-cdk#32]
Hello again, Since the server handler is Edge, what is the best way to handle config/env variables?
I've read about custom headers but there's a limit.
SSM Parameter store might work but the cost might be a problem: access per deployment or per new lambda invocation.

**Comment by juranki** [comment]
At the moment there is a possibility to specify environment variables to the server like this:

```typescript
    ...
    const svelteSite = new SvelteDistribution(this, 'svelteDistribution', {
      rendererProps: {
        environment: {
          API_ENDPOINT: apiEndpoint
        }
      }
    })
    ...
```
The values are passed in custom headers. Handler loads them into environment variables before invoking application code. The limits you mentioned apply, but I think it's possible to request a higher quota for the number of headers.

**Comment by khuezy** [comment]
Thanks!
